"""Dependency-free visual system for generated auction review reports."""

# The renderer inlines this stylesheet. Generated reports therefore remain a
# single offline file and do not inherit the visual language of a dashboard UI.
REPORT_CSS = r"""
:root { --paper:#f5f2eb; --surface:#fffdf8; --ink:#1f2933; --muted:#64707d; --line:#d7d1c6; --line-dark:#a69f92; --navy:#1c3244; --green:#176b55; --green-soft:#e7f2ed; --amber:#9b5c09; --amber-soft:#fff3d6; --red:#a33644; --red-soft:#fbedee; --serif:"Iowan Old Style","AppleMyungjo","Noto Serif KR",Georgia,serif; --sans:-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo","Noto Sans KR",sans-serif; }
* { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; background:var(--paper); color:var(--ink); font:15px/1.72 var(--sans); letter-spacing:-.012em; } main { max-width:1040px; margin:auto; padding:26px 24px 86px; } h1,h2,h3 { color:var(--navy); line-height:1.3; letter-spacing:-.035em; } h1 { margin:0; font:700 clamp(30px,5vw,46px)/1.16 var(--serif); } h2 { margin:48px 0 14px; font-size:23px; } h3 { margin:0 0 7px; font-size:16px; } p { margin:8px 0; } a { color:#075f85; text-underline-offset:3px; } .fine,.sub { color:var(--muted); }
.eyebrow,.section-label { margin:0 0 8px; color:#536272; font-size:11px; font-weight:800; letter-spacing:.1em; text-transform:uppercase; }.report-header { padding:21px 0 24px; border-top:6px solid var(--navy); border-bottom:1px solid var(--line-dark); }.report-header .sub { max-width:760px; margin-top:12px; font-size:15px; }.meta { display:flex; flex-wrap:wrap; gap:7px 18px; margin-top:17px; color:var(--muted); font-size:13px; }.chip { display:inline-flex; align-items:center; gap:5px; }.chip::before { content:"·"; color:var(--navy); font-weight:900; }
.caution-banner { margin:20px 0 26px; padding:13px 15px; border-left:4px solid var(--amber); background:var(--amber-soft); color:#553600; font-size:14px; }.caution-banner strong { color:#714100; }.source-line { margin:8px 0 0; padding-top:9px; border-top:1px solid #e3ca98; }
.decision-sheet { display:grid; grid-template-columns:minmax(0,1.8fr) minmax(230px,.8fr); gap:28px; padding:30px 0 27px; border-bottom:2px solid var(--navy); }.decision-sheet h2 { margin:8px 0; font:700 clamp(24px,3vw,34px)/1.32 var(--serif); }.verdict-label { display:inline-block; margin:0; padding:3px 9px; border:1px solid var(--green); color:#075941; background:var(--green-soft); font-size:13px; font-weight:800; }.verdict-meta { padding:16px 0 0 19px; border-left:1px solid var(--line-dark); }.verdict-meta span { display:block; margin-bottom:13px; color:var(--muted); font-size:13px; }.verdict-meta strong { display:block; margin-top:1px; color:var(--ink); font-size:15px; }
.next-actions { margin-top:24px; padding:18px 20px; background:var(--navy); color:#f8f4ec; }.next-actions h2 { margin:0 0 10px; color:#fffaf0; font:700 19px/1.35 var(--serif); }.next-actions ol { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:14px; margin:0; padding:0; list-style:none; counter-reset:action; }.next-actions li { position:relative; padding-left:30px; font-size:14px; }.next-actions li::before { counter-increment:action; content:counter(action); position:absolute; top:0; left:0; width:21px; height:21px; border:1px solid #92a7b7; border-radius:50%; text-align:center; font-size:12px; line-height:19px; }.next-actions strong { display:block; color:#fff; font-size:14px; }
.section-intro { max-width:720px; margin:0 0 14px; color:var(--muted); }.brief-grid { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); border-top:1px solid var(--line-dark); border-bottom:1px solid var(--line-dark); }.brief-card { min-height:152px; padding:17px 16px 15px; border-right:1px solid var(--line); background:transparent; }.brief-card:first-child { padding-left:0; }.brief-card:last-child { padding-right:0; border-right:0; }.brief-card h3 { margin-bottom:7px; font:700 18px/1.35 var(--serif); }.brief-card .eyebrow { margin-bottom:5px; }.brief-card.favorable h3::before,.brief-card.caution h3::before,.brief-card.high_risk h3::before,.brief-card.unknown h3::before { display:inline-block; margin-right:6px; font:800 11px/1 var(--sans); letter-spacing:.04em; vertical-align:2px; }.brief-card.favorable h3::before { content:"통과"; color:var(--green); }.brief-card.caution h3::before { content:"확인"; color:var(--amber); }.brief-card.high_risk h3::before { content:"위험"; color:var(--red); }.brief-card.unknown h3::before { content:"보류"; color:var(--muted); }
.conclusions { display:grid; gap:0; border-top:1px solid var(--line-dark); }.conclusion { position:relative; padding:23px 0 24px 52px; border-bottom:1px solid var(--line); background:transparent; }.conclusion::before { content:"검토"; position:absolute; top:25px; left:0; color:var(--green); font-size:11px; font-weight:800; letter-spacing:.08em; }.conclusion h3 { margin-bottom:12px; font:700 20px/1.45 var(--serif); }.conclusion p { display:grid; grid-template-columns:142px minmax(0,1fr); gap:14px; margin:5px 0; }.conclusion strong { color:var(--muted); font-size:13px; }.legal { margin-top:12px; padding:0; border:0; background:transparent; }.legal summary { color:#075f85; font-size:13px; }
.breaker { margin:25px 0 0; padding:19px 20px 17px; border:1px solid #e7b8be; background:var(--red-soft); }.breaker h2 { margin:0 0 8px; color:var(--red); font:700 19px/1.35 var(--serif); }.breaker ul { margin:0; padding-left:19px; }
.market-summary { position:relative; padding:20px; border-top:3px solid var(--green); background:#edf5f1; }.market-summary strong { color:var(--green); font:700 19px/1.35 var(--serif); }.price-ladder { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin:16px 0 2px; }.price-point { padding-top:8px; border-top:5px solid var(--line-dark); }.price-point.minimum { border-color:var(--green); }.price-point span { display:block; color:var(--muted); font-size:12px; }.price-point b { display:block; margin-top:2px; color:var(--navy); font:700 17px/1.35 var(--serif); }
.deep-review,.scope,.evidence-panel { margin-top:28px; padding:15px 17px; border:1px solid var(--line); background:var(--surface); }.deep-review>summary,.scope>summary,.evidence-panel>summary { cursor:pointer; color:var(--navy); font:700 17px/1.35 var(--serif); }.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:12px; margin-top:16px; }.card,.decision { padding:16px; border:1px solid var(--line); background:#fffefa; }.card.risk,.decision { border-left:4px solid var(--red); }.decision { margin-top:15px; background:var(--red-soft); }.decision-status { margin:0 0 6px; color:var(--red); font:800 20px/1.3 var(--serif); }.status { font-weight:800; }.confirmed { color:var(--green); }.conditional,.candidate,.unknown { color:var(--amber); }.withheld,.not_indicated { color:var(--red); }
.notice { margin-top:10px; padding:15px 18px; border-left:4px solid var(--amber); background:var(--amber-soft); } table { width:100%; border-collapse:collapse; background:var(--surface); font-size:14px; } th,td { padding:12px 11px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; } th { color:var(--navy); font-weight:800; background:#ece9e1; } tbody tr:last-child th,tbody tr:last-child td { border-bottom:0; }.evidence-list { display:grid; gap:10px; margin-top:14px; }.evidence-item { padding:14px 16px; border:1px solid var(--line); background:#faf8f3; scroll-margin-top:16px; }.evidence-item:target { border-color:var(--green); background:var(--green-soft); }.evidence-item h3 { margin:0 0 5px; }.evidence-item p { margin:4px 0; }.source-files { margin:12px 0; } details>summary { cursor:pointer; } code { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:.9em; }
@media (max-width:760px) { main { padding:18px 16px 56px; }.decision-sheet { grid-template-columns:1fr; gap:15px; }.verdict-meta { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; padding:13px 0 0; border-top:1px solid var(--line); border-left:0; }.verdict-meta span { margin:0; }.next-actions ol { grid-template-columns:1fr; gap:10px; }.brief-grid { grid-template-columns:1fr 1fr; }.brief-card:nth-child(2) { border-right:0; }.brief-card:nth-child(n+3) { border-top:1px solid var(--line); }.brief-card:nth-child(3) { padding-left:0; }.conclusion p { grid-template-columns:1fr; gap:1px; margin:10px 0; } }
@media (max-width:480px) { .meta { display:grid; gap:4px; }.brief-grid,.verdict-meta,.price-ladder { grid-template-columns:1fr; }.brief-card,.brief-card:nth-child(2) { padding:15px 0; border-right:0; border-top:1px solid var(--line); }.brief-card:first-child { border-top:0; }.conclusion { padding-left:0; }.conclusion::before { position:static; display:block; margin-bottom:6px; } }
@media print { body { background:#fff; color:#000; font-size:10.5px; } main { max-width:none; padding:0; }.caution-banner,.next-actions,.market-summary,.breaker { print-color-adjust:exact; -webkit-print-color-adjust:exact; }.deep-review,.scope,.evidence-panel,.conclusion,.card,table { break-inside:avoid; } a { color:#000; text-decoration:none; } }
"""
